packaging_format = 2

id = "glpi"
name = "GLPI"
description.en = "IT Asset Management"
description.fr = "Gestion des services informatiques (ITSM)"

version = "11.0.4~ynh1"

maintainers = []

[upstream]
license = "GPL-2.0"
website = "https://glpi-project.org"
admindoc = "https://glpi-install.readthedocs.io/en/latest/"
code = "https://github.com/glpi-project/glpi"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/glpi"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/glpi-project/glpi/releases/download/11.0.4/glpi-11.0.4.tgz"
    sha256 = "a763297081a0085a72039efe67e1705c18101ef0c0ebca41c3c249f74055ee03"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "^glpi-.*\\.tgz"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "mariadb-server",
        "php8.3-cli",
        "php8.3-curl",
        "php8.3-fileinfo",
        "php8.3-gd",
        "php8.3-mbstring",
        "php8.3-mysqli",
        "php8.3-simplexml",
        "php8.3-xml",
        "php8.3-intl",
        "php8.3-ldap",
        "php8.3-xmlrpc",
        "php8.3-bz2",
        "php8.3-zip",
        "php8.3-bcmath",
    ]

    [resources.database]
    type = "mysql"
